version: '3.8'

services:
  backend:
    build: 
      context: ./backend/app
      dockerfile: Dockerfile
    container_name: travel-advisor-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: travel-advisor-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: travel-advisor-network
